from fpdf import FPDF
from datetime import datetime
import json
from io import BytesIO
from jinja2 import Template

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Vaptiq.ai Security Assessment', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'CONFIDENTIAL - Generated by Vaptiq.ai - Page {self.page_no()}', 0, 0, 'C')

class ReportGenerator:
    @staticmethod
    def clean_text(text):
        """Sanitize text to remove non-latin characters that might break FPDF."""
        if not text: return ""
        # Replace common problematic characters (using Unicode escapes to avoid quote issues)
        text = text.replace('\u2019', "'").replace('\u201c', '"').replace('\u201d', '"').replace('\u2013', '-')
        # Keep only latin-1 characters
        return text.encode('latin-1', 'replace').decode('latin-1')

    @staticmethod
    def generate_pdf(scan_result):
        pdf = PDFReport()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # --- Cover Page ---
        pdf.set_font('Helvetica', 'B', 24)
        pdf.set_text_color(33, 37, 41)
        pdf.cell(0, 60, '', 0, 1) # Spacer
        pdf.cell(0, 10, 'Confidential Security Assessment', 0, 1, 'C')
        pdf.ln(10)
        
        pdf.set_font('Helvetica', '', 14)
        target = ReportGenerator.clean_text(scan_result.get('target', 'Unknown'))
        pdf.cell(0, 10, f"Target: {target}", 0, 1, 'C')
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 0, 1, 'C')
        pdf.ln(20)
        
        # Logo placeholder (text for now)
        pdf.set_font('Courier', 'B', 16)
        pdf.set_text_color(16, 185, 129) # Emerald 500
        pdf.cell(0, 10, '[ VAPTIQ.AI ]', 0, 1, 'C')
        pdf.ln(20)
        
        # --- Executive Summary ---
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(33, 37, 41)
        pdf.cell(0, 10, 'Executive Summary', 0, 1)
        pdf.ln(5)
        
        findings = scan_result.get('findings', [])
        
        # Count severities
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for f in findings:
            sev = f.get('severity', 'LOW').upper()
            if sev in counts:
                counts[sev] += 1
                
        pdf.set_font('Helvetica', '', 12)
        pdf.cell(0, 10, f"Total Findings: {len(findings)}", 0, 1)
        pdf.ln(5)
        
        # Simple table
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(40, 10, 'Severity', 1)
        pdf.cell(40, 10, 'Count', 1)
        pdf.ln()
        
        pdf.set_font('Helvetica', '', 12)
        for sev, count in counts.items():
            if sev == 'CRITICAL': pdf.set_text_color(220, 53, 69)
            elif sev == 'HIGH': pdf.set_text_color(253, 126, 20)
            elif sev == 'MEDIUM': pdf.set_text_color(255, 193, 7)
            else: pdf.set_text_color(13, 110, 253)
            
            pdf.cell(40, 10, sev, 1)
            pdf.cell(40, 10, str(count), 1)
            pdf.ln()
            
        pdf.set_text_color(0, 0, 0) # Reset
        
        # --- Detailed Findings ---
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 16)
        pdf.cell(0, 10, 'Detailed Findings', 0, 1)
        pdf.ln(5)
        
        for finding in findings:
            # Title & Severity
            pdf.set_font('Helvetica', 'B', 14)
            severity = finding.get('severity', 'LOW').upper()
            
            if severity == 'CRITICAL': pdf.set_text_color(220, 53, 69)
            elif severity == 'HIGH': pdf.set_text_color(253, 126, 20)
            elif severity == 'MEDIUM': pdf.set_text_color(255, 193, 7)
            else: pdf.set_text_color(13, 110, 253)
                
            title = ReportGenerator.clean_text(finding.get('type', 'Vulnerability'))
            pdf.cell(0, 10, f"[{severity}] {title}", 0, 1)
            pdf.set_text_color(0, 0, 0) # Reset
            
            # Status
            pdf.set_font('Helvetica', 'B', 10)
            status = "CONFIRMED" # Mock status
            if status == "CONFIRMED":
                pdf.set_text_color(25, 135, 84) # Green
            else:
                pdf.set_text_color(108, 117, 125) # Gray
            pdf.cell(0, 10, f"Status: {status}", 0, 1)
            pdf.set_text_color(0, 0, 0)
            
            # Description
            pdf.set_font('Helvetica', '', 11)
            description = ReportGenerator.clean_text(finding.get('description', 'No description provided.'))
            pdf.multi_cell(0, 6, f"Description: {description}")
            pdf.ln(2)
            
            # Proof of Exploit
            proof = finding.get('proof', None)
            if proof:
                proof = ReportGenerator.clean_text(proof)
                pdf.ln(2)
                pdf.set_fill_color(245, 245, 245) # Light Gray
                pdf.set_font('Courier', '', 9)
                
                # Calculate height needed
                # A rough estimation: 5mm per line
                lines = proof.count('\n') + 1
                height = lines * 5 + 10
                
                # Check if we need a page break
                if pdf.get_y() + height > 270:
                    pdf.add_page()
                
                pdf.rect(x=pdf.get_x(), y=pdf.get_y(), w=190, h=height, style='F')
                pdf.set_xy(pdf.get_x() + 2, pdf.get_y() + 2)
                pdf.multi_cell(186, 5, f"PROOF OF EXPLOIT:\n{proof}")
                pdf.ln(5)
                
            pdf.ln(10)
            # Line separator
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
            pdf.ln(10)
            
        # FPDF.output() returns a bytes object when dest='S' is used. Wrap it in BytesIO.
        pdf_bytes = pdf.output(dest='S').encode('latin-1') if isinstance(pdf.output(dest='S'), str) else pdf.output(dest='S')
        return BytesIO(pdf_bytes)

    @staticmethod
    def generate_html(scan_result):
        # Use Jinja2 Template to prevent XSS via auto-escaping
        template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Vaptiq.ai Report - {{ target }}</title>
            <style>
                body { background-color: #09090b; color: #e4e4e7; font-family: system-ui, sans-serif; padding: 40px; line-height: 1.5; }
                .container { max-width: 900px; margin: 0 auto; }
                h1 { color: #10b981; font-size: 2.5rem; margin-bottom: 0.5rem; }
                .meta { color: #a1a1aa; margin-bottom: 3rem; }
                .finding { background-color: #18181b; padding: 24px; margin-bottom: 24px; border-radius: 12px; border: 1px solid #27272a; }
                .finding h3 { margin-top: 0; display: flex; align-items: center; gap: 12px; }
                .badge { padding: 4px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }
                .critical { background-color: rgba(239, 68, 68, 0.1); color: #ef4444; }
                .high { background-color: rgba(249, 115, 22, 0.1); color: #f97316; }
                .medium { background-color: rgba(234, 179, 8, 0.1); color: #eab308; }
                .low { background-color: rgba(59, 130, 246, 0.1); color: #3b82f6; }
                .proof { background-color: #000; padding: 16px; font-family: monospace; border-radius: 6px; border: 1px solid #27272a; margin-top: 16px; white-space: pre-wrap; color: #10b981; }
                .footer { margin-top: 60px; text-align: center; color: #52525b; font-size: 0.875rem; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Vaptiq.ai Report</h1>
                <div class="meta">
                    <p>Target: <strong>{{ target }}</strong></p>
                    <p>Date: {{ timestamp }}</p>
                </div>
                
                <h2>Detailed Findings</h2>

                {% for finding in findings %}
                <div class="finding">
                    <h3>
                        <span class="badge {{ finding.severity|lower }}">{{ finding.severity }}</span>
                        {{ finding.type }}
                    </h3>
                    <p>{{ finding.description }}</p>
                    {% if finding.proof %}
                    <div class="proof">PROOF OF EXPLOIT:<br>{{ finding.proof }}</div>
                    {% endif %}
                </div>
                {% endfor %}

                <div class="footer">
                    CONFIDENTIAL - Generated by Vaptiq.ai
                </div>
            </div>
        </body>
        </html>
        """

        template = Template(template_str, autoescape=True)
        html = template.render(
            target=scan_result.get('target', ''),
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            findings=scan_result.get('findings', [])
        )

        return BytesIO(html.encode('utf-8'))

    @staticmethod
    def generate_json(scan_result):
        return BytesIO(json.dumps(scan_result, indent=2).encode('utf-8'))
